//
//  Datos..swift
//  Hamburguesas
//
//  Created by JOSE EFRAIN BALLADO LUNA on 08/05/16.
//  Copyright © 2016 LinSunJa. All rights reserved.
//

import Foundation
import UIKit

class ColeccionDePaises {
    let paises = ["Afganistán",
                  "Albania",
                  "Alemania",
                  "Andorra",
                  "Angola",
                  "Antigua y Barbuda",
                  "Arabia Saudita",
                  "Argelia",
                  "Argentina",
                  "Armenia",
                  "Australia",
                  "Austria",
                  "Azerbaiyán",
                  "Bahamas",
                  "Bangladés",
                  "Barbados",
                  "Baréin",
                  "Bélgica",
                  "Belice",
                  "Benín",
                  "Bielorrusia",
                  "Birmania",
                  "Bolivia",
                  "Bosnia y Herzegovina",
                  "Botsuana",
                  "Brasil",
                  "Brunéi",
                  "Bulgaria",
                  "Burkina Faso",
                  "Burundi",
                  "Bután",
                  "Cabo Verde",
                  "Camboya",
                  "Camerún",
                  "Canadá",
                  "Catar",
                  "Chad",
                  "Chile",
                  "China",
                  "Chipre",
                  "Ciudad del Vaticano",
                  "Colombia",
                  "Comoras",
                  "Corea del Norte",
                  "Corea del Sur",
                  "Costa de Marfil",
                  "Costa Rica",
                  "Croacia",
                  "Cuba",
                  "Dinamarca",
                  "Dominica",
                  "Ecuador",
                  "Egipto",
                  "El Salvador",
                  "Emiratos Árabes Unidos",
                  "Eritrea",
                  "Eslovaquia",
                  "Eslovenia",
                  "España",
                  "Estados Unidos",
                  "Estonia",
                  "Etiopía",
                  "Filipinas",
                  "Finlandia",
                  "Fiyi",
                  "Francia",
                  "Gabón",
                  "Gambia",
                  "Georgia",
                  "Ghana",
                  "Granada",
                  "Grecia",
                  "Guatemala",
                  "Guyana",
                  "Guinea",
                  "Guinea ecuatorial",
                  "Guinea-Bisáu",
                  "Haití",
                  "Honduras",
                  "Hungría",
                  "India",
                  "Indonesia",
                  "Irak",
                  "Irán",
                  "Irlanda",
                  "Islandia",
                  "Islas Marshall",
                  "Islas Salomón",
                  "Israel",
                  "Italia",
                  "Jamaica",
                  "Japón",
                  "Jordania",
                  "Kazajistán",
                  "Kenia",
                  "Kirguistán",
                  "Kiribati",
                  "Kuwait",
                  "Laos",
                  "Lesoto",
                  "Letonia",
                  "Líbano",
                  "Liberia",
                  "Libia",
                  "Liechtenstein",
                  "Lituania",
                  "Luxemburgo",
                  "Madagascar",
                  "Malasia",
                  "Malaui",
                  "Maldivas",
                  "Malí",
                  "Malta",
                  "Marruecos",
                  "Mauricio",
                  "Mauritania",
                  "México",
                  "Micronesia",
                  "Moldavia",
                  "Mónaco",
                  "Mongolia",
                  "Montenegro",
                  "Mozambique",
                  "Namibia",
                  "Nauru",
                  "Nepal",
                  "Nicaragua",
                  "Níger",
                  "Nigeria",
                  "Noruega",
                  "Nueva Zelanda",
                  "Omán",
                  "Países Bajos",
                  "Pakistán",
                  "Palaos",
                  "Panamá",
                  "Papúa Nueva Guinea",
                  "Paraguay",
                  "Perú",
                  "Polonia",
                  "Portugal",
                  "Reino Unido",
                  "República Centroafricana",
                  "República Checa",
                  "República de Macedonia",
                  "República del Congo",
                  "República Democrática del Congo",
                  "República Dominicana",
                  "República Sudafricana",
                  "Ruanda",
                  "Rumanía",
                  "Rusia",
                  "Samoa",
                  "San Cristóbal y Nieves",
                  "San Marino",
                  "San Vicente y las Granadinas",
                  "Santa Lucía",
                  "Santo Tomé y Príncipe",
                  "Senegal",
                  "Serbia",
                  "Seychelles",
                  "Sierra Leona",
                  "Singapur",
                  "Siria",
                  "Somalia",
                  "Sri Lanka",
                  "Suazilandia",
                  "Sudán",
                  "Sudán del Sur",
                  "Suecia",
                  "Suiza",
                  "Surinam",
                  "Tailandia",
                  "Tanzania",
                  "Tayikistán",
                  "Timor Oriental",
                  "Togo",
                  "Tonga",
                  "Trinidad y Tobago",
                  "Túnez",
                  "Turkmenistán",
                  "Turquía",
                  "Tuvalu",
                  "Ucrania",
                  "Uganda",
                  "Uruguay",
                  "Uzbekistán",
                  "Vanuatu",
                  "Venezuela",
                  "Vietnam",
                  "Yemen",
                  "Yibuti",
                  "Zambia",
                  "Zimbabue"]
    
    func obtenPais() -> String {
        let position = Int(arc4random()) % paises.count
        print(position)
        return paises[position]
    }
}

class ColeccionDeHamburguesas {
    let hamburguesas = ["CORRALÍSIMA ½ LIBRA:\nMedia libra de carne de res asada a la parrilla, con salsa BBQ.",
                        "CORRALÍSIMA ¾ DE LIBRA:\nTres cuartos de libra de carne de res asada a la parrilla, con salsa BBQ.",
                        "CORRAL CASERA:\n1/3 Lb. De carne de res, con queso americano, cebolla roja recién cortada, tomate y lechuga fresca.",
                        "CORRALÍSIMA TODOTERRENO\nDos porciones de ¼ de lb. De carne de res asada a la parrilla, con tocineta, queso mozzarela, vegetales, pepinillos y salsa BBQ.",
                        "CORRAL\nLa tradicional con ¼ lb. de carne de res, lechuga fresca, tomate y cebolla recién cortados. Salsas y las adiciones que prefieras.",
                        "CORRAL CON QUESO:\nLa tradicional con queso mozzarella, verduras frescas y salsas.",
                        "CORRAL ESPECIAL:\nCarne, lechuga, tomate, cebolla, salsas con tocineta en trocitos y queso mozzarella.",
                        "CORRAL HAWAIANA:\nCon queso mozzarella, piña, salsas y lechuga fresca.",
                        "CORRAL CRIOLLA:\nCon queso mozzarella, huevo frito y cebolla grille.",
                        "CORRAL MEXICANA:\nCarne, lechuga, tomate, cebolla, salsas con queso americano, frijol refrito y guacamole.",
                        "CORRAL COSTEÑA:\nCon la deliciosa combinación de chips de plátano, suero y queso costeño.",
                        "CORRALITO HAMBURGUESA:\nCon Hamburguesa de 90gr. o Lomitos de Pollo, papas a la francesa, jugo o gaseosa pequeña y dulce sorpresa.",
                        "CORRALITA:\nCon carne de 90 gr. acompañada con Lechuga en Julianas.",
                        "Corralera:\n1/4 de libra de 100% carne de res a la plancha, con Tocineta, Queso Colby, Cebolla Grillé en Pétalos, Salsa BBQ, Mayonesa y Salsa de tomate.",
                        "CALLEJERA:\n1/4 de libra de 100% Carne de res a la plancha, Queso Mozzarella, Papa Perro, Salsa de tomate, Mostaza y Mayonesa",
                        "VAQUERO ESPECIAL:\nCon queso mozzarella, tocineta, cebolla picada, papas chips trituradas y salsas.",
                        "SÁNDWICH POLLO:\nPechuga de pollo a la plancha con salsa BBQ, tomate y cebolla recién cortados, lechuga fresca y mayonesa.",
                        "PHILADELPHIA STEAK:\nFinas tajadas de excepcional lomo ancho de res asadas a la plancha, con cebolla grillé, queso americano y mayonesa.",
                        "McGuire’s Grand Burger:\nServida en el McGuire’s Irish Pub en Pensacola, Florida.Lleva un filete mignon acompañada por una botella de Moet & Chandon white star champagne.",
                        "Million Rupiah Burger:\nDentro de sus ingredientes exóticos se incluye el foie gras, hongos portobello y peras coreanas.",
                        "The DB Royale Double Truffle Burger:\nEs la especialidad del DB Bistro Moderne. Está rellena con carne de costillas pasadas por vino tinto, foie gras y trufas negras.",
                        "Richard Nouveau Burger:\nEspolvoreada con 25 gramos de hojuelas de oro, un toque de foie gras y unos trozos de un viejo gruyere gratinados.",
                        "The Burger:\nPuedes degustar esta hamburguesa con carne Wagyu, trufas blancas, rebanadas de jamon Pata Negra, cebolla cristalizada, carne de cordero con un poco de sal rosa del Himalaya, y un toque de vinagre balsámico de Modena. El pan es horneado cuidadosamente con vino blanco y una infusión de mayonesa con trufas blancas.",
                        "Serendipity Burger:\nPreparada con una mezcla de carne Wagyu, hierbas finas, mantequilla de trufas blancas y sazonada con sal ahumada del pacífico y con un toque de queso cheddar gratinado. Moldeada a mano y acompañada con trufas negras, caviar Kaluga que puede ser saboreada.",
                        "Absolutely Ridiculous Burger:\nEs absolutamente grande, con un peso de 185.6 libras, se hizo acreedora del record Guiness a la hamburguesa más grande.",
                        "Douche Burger:\nLleva foie gras mezclado en la carne, láminas de queso gruyere que han sido pasadas por champagne, un poco de langosta, caviar, trufas y salsa BBQ hecha con granos del más exótico café: Kopi Luwak.",
                        "Kobe Beef and Maine Lobster Burger:\nMoldeada a mano y con carne Kobe y de langosta mezcladas, le añaden cebollas caramelizadas, queso Brie importado y aderezada con un vinagre balsámico con 100 años de conservación y para acompañar va con una botella de Dom Perignon. Una cena muy exclusiva.",
                        "FleurBurger 5000:\nUna hamburguesa muy exclusiva, servida con foie grass, una salsa de truffas, el pan está hecho con trufas negras y acompañada por una botella de Chateau Petrus 1990 y una guarnición de papas doradas a las finas hierbas."]
    
    
    func obtenHamburguesa() -> String {
        let position = Int(arc4random()) % hamburguesas.count
        return hamburguesas[position]
    }
    
}

struct Colores {
    
    let colores = [UIColor (red: 210/250, green: 90/255, blue: 45/255, alpha: 1),
                   UIColor (red: 40/250, green: 170/255, blue: 45/255, alpha: 1),
                   UIColor (red: 3/250, green: 180/255, blue: 90/255, alpha: 1),
                   UIColor (red: 210/250, green: 190/255, blue: 5/255, alpha: 1),
                   UIColor (red: 120/250, green: 120/255, blue: 50/255, alpha: 1),
                   UIColor (red: 130/250, green: 80/255, blue: 90/255, alpha: 1),
                   UIColor (red: 130/250, green: 130/255, blue: 130/255, alpha: 1),
                   UIColor (red: 3/250, green: 50/255, blue: 90/255, alpha: 1)]
    
    func regresaAleatorio() -> UIColor {
        let posicion = Int(arc4random()) % colores.count
        return colores [posicion]
    }
}

